In [1]:
import xarray as xr
import numpy as np

In [11]:
path = '/projects/0/einf2878/ROMS'
data_type = 'ECCO'
clim = xr.open_dataset(f'{path}/data/{data_type}/forcing_output/NorthSea4_clim_ECCO_1992116_to_20171216.nc')
forcing_input = xr.open_dataset(f'{path}/data/{data_type}/forcing_input/forcing_input.nc')

In [17]:
clim.zeta.isel(ocean_time = 0)

<xarray.DataArray 'zeta' (eta_rho: 110, xi_rho: 122)>
array([[-0.249048, -0.249048, -0.249048, ...,       nan,       nan,       nan],
       [-0.249048, -0.249335, -0.249334, ...,       nan,       nan,       nan],
       [-0.283699, -0.270224, -0.270223, ...,       nan,       nan,       nan],
       ...,
       [-0.704772, -0.702034, -0.701716, ...,       nan,       nan,       nan],
       [-0.704772, -0.704386, -0.704004, ...,       nan,       nan,       nan],
       [-0.704772, -0.704772, -0.703984, ...,       nan,       nan,       nan]])
Coordinates:
    ocean_time  datetime64[ns] 1992-01-16
Dimensions without coordinates: eta_rho, xi_rho
Attributes:
    long_name:  sea level
    units:      meter
    time:       ocean_time
    field:      sea level, scalar, series

In [41]:
clim.zeta

<xarray.DataArray 'zeta' (ocean_time: 312, eta_rho: 110, xi_rho: 122)>
array([[[-0.249048, -0.249048, ...,       nan,       nan],
        [-0.249048, -0.249335, ...,       nan,       nan],
        ...,
        [-0.704772, -0.704386, ...,       nan,       nan],
        [-0.704772, -0.704772, ...,       nan,       nan]],

       [[-0.242163, -0.242163, ...,       nan,       nan],
        [-0.242163, -0.242467, ...,       nan,       nan],
        ...,
        [-0.74009 , -0.739444, ...,       nan,       nan],
        [-0.74009 , -0.74009 , ...,       nan,       nan]],

       ...,

       [[-0.120618, -0.120618, ...,       nan,       nan],
        [-0.120618, -0.120707, ...,       nan,       nan],
        ...,
        [-0.647398, -0.646558, ...,       nan,       nan],
        [-0.647398, -0.647398, ...,       nan,       nan]],

       [[-0.140061, -0.140061, ...,       nan,       nan],
        [-0.140061, -0.14014 , ...,       nan,       nan],
        ...,
        [-0.67433 , -0.673916, ...,       nan,       nan],
        [-0.67433 , -0.67433 , ...,       nan,       nan]]])
Coordinates:
  * ocean_time  (ocean_time) datetime64[ns] 1992-01-16 1992-02-16 ... 2017-12-16
Dimensions without coordinates: eta_rho, xi_rho
Attributes:
    long_name:  sea level
    units:      meter
    time:       ocean_time
    field:      sea level, scalar, series

In [42]:
xr.where(clim.zeta.isnull(), -9.99e33, clim.zeta).isel(ocean_time = 0)

<xarray.DataArray 'zeta' (eta_rho: 110, xi_rho: 122)>
array([[-2.49048271e-01, -2.49048271e-01, -2.49048271e-01, ...,
        -9.99000000e+33, -9.99000000e+33, -9.99000000e+33],
       [-2.49048271e-01, -2.49335014e-01, -2.49333852e-01, ...,
        -9.99000000e+33, -9.99000000e+33, -9.99000000e+33],
       [-2.83699297e-01, -2.70224357e-01, -2.70223191e-01, ...,
        -9.99000000e+33, -9.99000000e+33, -9.99000000e+33],
       ...,
       [-7.04772093e-01, -7.02034225e-01, -7.01715539e-01, ...,
        -9.99000000e+33, -9.99000000e+33, -9.99000000e+33],
       [-7.04772093e-01, -7.04385932e-01, -7.04003763e-01, ...,
        -9.99000000e+33, -9.99000000e+33, -9.99000000e+33],
       [-7.04772093e-01, -7.04772093e-01, -7.03984477e-01, ...,
        -9.99000000e+33, -9.99000000e+33, -9.99000000e+33]])
Coordinates:
    ocean_time  datetime64[ns] 1992-01-16
Dimensions without coordinates: eta_rho, xi_rho

In [34]:
clim.zeta.isnull().values

array([[[False, False, False, ...,  True,  True,  True],
        [False, False, False, ...,  True,  True,  True],
        [False, False, False, ...,  True,  True,  True],
        ...,
        [False, False, False, ...,  True,  True,  True],
        [False, False, False, ...,  True,  True,  True],
        [False, False, False, ...,  True,  True,  True]],

       [[False, False, False, ...,  True,  True,  True],
        [False, False, False, ...,  True,  True,  True],
        [False, False, False, ...,  True,  True,  True],
        ...,
        [False, False, False, ...,  True,  True,  True],
        [False, False, False, ...,  True,  True,  True],
        [False, False, False, ...,  True,  True,  True]],

       [[False, False, False, ...,  True,  True,  True],
        [False, False, False, ...,  True,  True,  True],
        [False, False, False, ...,  True,  True,  True],
        ...,
        [False, False, False, ...,  True,  True,  True],
        [False, False, False, ...,  True,  Tr

In [43]:
result = xr.open_dataset(f'{path}/data/{data_type}/forcing_output/result.nc')

In [46]:
result.zeta.isel(time=0)

<xarray.DataArray 'zeta' (eta_rho: 110, xi_rho: 122)>
array([[-0.249048, -0.249048, -0.249048, ...,       nan,       nan,       nan],
       [-0.249048, -0.249335, -0.249334, ...,       nan,       nan,       nan],
       [-0.283699, -0.270224, -0.270223, ...,       nan,       nan,       nan],
       ...,
       [-0.704772, -0.702034, -0.701716, ...,       nan,       nan,       nan],
       [-0.704772, -0.704386, -0.704004, ...,       nan,       nan,       nan],
       [-0.704772, -0.704772, -0.703984, ...,       nan,       nan,       nan]])
Coordinates:
    time     datetime64[ns] 1992-01-16T12:00:00
  * eta_rho  (eta_rho) int64 0 1 2 3 4 5 6 7 ... 102 103 104 105 106 107 108 109
  * xi_rho   (xi_rho) int64 0 1 2 3 4 5 6 7 ... 114 115 116 117 118 119 120 121